### PR TITLE
CSSParserVisitorImpl avoid allocating debug strings when debug is disabled

### PR DESCRIPTION
**Pull request by dmercuriali**
Added if (log.isDebugEnabled()) around debug statements to avoid string allocation

### CODE REVIEW

**Comment by eolivelli** [comment]
I am hitting this same problem.
Is there a reason for the -1 ?

**Comment by radkovo** [comment]
Thanks for the PR. But I am afraid, I can see quite many problems in it:

- It does not fix the problem, it just mutes the symptoms. The real source of the problem is probably hidden deep in the parser code because neither `operator` nor `keyword` should be `null`.
- It brings redundant checks to the code. The `log.isDebugEnabled()` tests are redundant in most cases because the `log.debug()` call does the same test internally.
- The problem is reported for different jStyleParser version than you fix by this PR.

I will add a proposal of the solution to the corresponding issue #100.

**Comment by eolivelli** [comment]
Btw I think that is a good practice to use 'isDebugEnabled'  because in general you are saving calls to toString() and so saving allocations.

**Comment by eolivelli** [comment]
IMHO this PR is worth to commit because we are saving resources.

I agree that the root cause is not fixed.
We are using this parser in hot paths in our code.
It would be great to work at higher level and reduce allocations as much as possible

**Comment by hrj** [comment]
@eolivelli For the problem of string allocations, I suggest making a separate PR.

One solution could be to use lambdas: `log.debug()` (or equivalent method) could take a parameter of SAM type. If debugging is enabled, only then it will invoke the SAM and thus strings will be created only when required. The implementation of lambdas is already optimised by JVMs; classes are only created if the lambda is called, and this combined with JIT compilation should eliminate any overheads.

In any case, it would be good to benchmark all approaches before going down a particular path.

**Comment by radkovo** [comment]
@eolivelli Ok, your comments regarding the efficiency seem reasonable. If there is a separate PR with this purpose, I will merge it. I was thinking about removing the `debug() ` calls completely but I need them occasionally when hunting for a parser bug.

Regarding the NPE issue #100 : is there a test case available? I would love to discover the source of the problem. @eolivelli @dmercuriali

**Pull request closed without merging**
