### PR TITLE
CSS animation and transition properties added.

### PR DESCRIPTION
**Pull request by dexterdd77**
Introduced _TestUtils_ as unified testing format.
Implemented representation and processing of properties related to CSS animation and transition.
Added tests for newly implemented properties.

### CODE REVIEW

**Comment by hrj** [comment]
@dexterdd77 Just curious to know, if you can share, where do you plan to use jStyleParser?

We are using jStyleParser in https://gngr.info

Since CSS animation would probably be used in an interactive app, I was wondering if there is any overlap / collaboration with gngr.

**Comment by dexterdd77** [comment]
@hrj Hey, yeah I personally don't plan anything particular with this project. These additions are part of my school project I'm doing for the founder @radkovo who requested them. I think there are others that build on my changes in jStyleParser and implement them in SwingBox. You should contact @radkovo for more details about this.
Thank you for your proposal though.

**Comment by radkovo** [comment]
It seems great, merged. Thanks!

**Comment by radkovo** [comment]
@hrj I am not aware of any project that would use this feature just now but CSS animations are becoming quite popular in web design in general so we are trying to keep up with the development.

**Pull request merged**
